
default: &default
  adapter: postgresql
  encoding: unicode
  database: railsreact_development
  pool: 5
  username: postgres
  password: BurSqlHan#007
  host: localhost
  port: 5432

development:
  <<: *default
  database: railsreact_development

test:
  <<: *default
  database: railsreact_test

production:
  <<: *default
  database: railsreact_production
  username: postgres
  password: BurSqlHan#007
